# Dockerfile
FROM ssoonan0770/soafee-practice:base

COPY process_object_detection.py process_object_detection.py
COPY entrypoint.sh entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh", "python3", "process_object_detection.py" ]