# Dockerfile
FROM ssoonan0770/soafee-practice:base

COPY process_lane_detection.py process_lane_detection.py
COPY entrypoint.sh entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh", "python3", "process_lane_detection.py" ]