# Dockerfile
FROM ssoonan0770/soafee-practice

COPY templates templates


COPY app.py app.py
COPY lane_detection_subscriber.py lane_detection_subscriber.py
COPY object_detection_subscriber.py object_detection_subscriber.py

ENV FLASK_APP=app.py \
    FLASK_RUN_HOST=0.0.0.0 \
    FLASK_RUN_PORT=5000

ENTRYPOINT [ "flask", "run"]