# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('ObjectDetection.dll')
if __package__ or '.' in __name__:
    from .. import _ObjectDetectionWrapper
else:
    import _ObjectDetectionWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ObjectDetectionWrapper.delete_SwigPyIterator

    def value(self):
        return _ObjectDetectionWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ObjectDetectionWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ObjectDetectionWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ObjectDetectionWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ObjectDetectionWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ObjectDetectionWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _ObjectDetectionWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _ObjectDetectionWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _ObjectDetectionWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ObjectDetectionWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ObjectDetectionWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ObjectDetectionWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ObjectDetectionWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ObjectDetectionWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ObjectDetectionWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ObjectDetectionWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ObjectDetectionWrapper:
_ObjectDetectionWrapper.SwigPyIterator_swigregister(SwigPyIterator)

FASTCDR_VERSION_MAJOR = _ObjectDetectionWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _ObjectDetectionWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _ObjectDetectionWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _ObjectDetectionWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _ObjectDetectionWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _ObjectDetectionWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _ObjectDetectionWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _ObjectDetectionWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class _BoundingBoxSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ObjectDetectionWrapper.delete__BoundingBoxSeq

# Register _BoundingBoxSeq in _ObjectDetectionWrapper:
_ObjectDetectionWrapper._BoundingBoxSeq_swigregister(_BoundingBoxSeq)

class BoundingBoxSeq(_BoundingBoxSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _ObjectDetectionWrapper.delete_BoundingBoxSeq

    def __init__(self, *args):
        _ObjectDetectionWrapper.BoundingBoxSeq_swiginit(self, _ObjectDetectionWrapper.new_BoundingBoxSeq(*args))

    def __len__(self):
        return _ObjectDetectionWrapper.BoundingBoxSeq___len__(self)

    def __getitem__(self, i):
        return _ObjectDetectionWrapper.BoundingBoxSeq___getitem__(self, i)

# Register BoundingBoxSeq in _ObjectDetectionWrapper:
_ObjectDetectionWrapper.BoundingBoxSeq_swigregister(BoundingBoxSeq)

class BoundingBox_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ObjectDetectionWrapper.BoundingBox_vector___nonzero__(self)

    def __bool__(self):
        return _ObjectDetectionWrapper.BoundingBox_vector___bool__(self)

    def __len__(self):
        return _ObjectDetectionWrapper.BoundingBox_vector___len__(self)

    def __getslice__(self, i, j):
        return _ObjectDetectionWrapper.BoundingBox_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ObjectDetectionWrapper.BoundingBox_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_vector___setitem__(self, *args)

    def pop(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_pop(self)

    def append(self, x):
        return _ObjectDetectionWrapper.BoundingBox_vector_append(self, x)

    def empty(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_empty(self)

    def size(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_size(self)

    def swap(self, v):
        return _ObjectDetectionWrapper.BoundingBox_vector_swap(self, v)

    def begin(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_begin(self)

    def end(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_end(self)

    def rbegin(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_rbegin(self)

    def rend(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_rend(self)

    def clear(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_clear(self)

    def get_allocator(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_get_allocator(self)

    def pop_back(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_pop_back(self)

    def erase(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_vector_erase(self, *args)

    def __init__(self, *args):
        _ObjectDetectionWrapper.BoundingBox_vector_swiginit(self, _ObjectDetectionWrapper.new_BoundingBox_vector(*args))

    def push_back(self, x):
        return _ObjectDetectionWrapper.BoundingBox_vector_push_back(self, x)

    def front(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_front(self)

    def back(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_back(self)

    def assign(self, n, x):
        return _ObjectDetectionWrapper.BoundingBox_vector_assign(self, n, x)

    def resize(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_vector_resize(self, *args)

    def insert(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_vector_insert(self, *args)

    def reserve(self, n):
        return _ObjectDetectionWrapper.BoundingBox_vector_reserve(self, n)

    def capacity(self):
        return _ObjectDetectionWrapper.BoundingBox_vector_capacity(self)
    __swig_destroy__ = _ObjectDetectionWrapper.delete_BoundingBox_vector

# Register BoundingBox_vector in _ObjectDetectionWrapper:
_ObjectDetectionWrapper.BoundingBox_vector_swigregister(BoundingBox_vector)

class _ObjectDetectionResultSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ObjectDetectionWrapper.delete__ObjectDetectionResultSeq

# Register _ObjectDetectionResultSeq in _ObjectDetectionWrapper:
_ObjectDetectionWrapper._ObjectDetectionResultSeq_swigregister(_ObjectDetectionResultSeq)

class ObjectDetectionResultSeq(_ObjectDetectionResultSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _ObjectDetectionWrapper.delete_ObjectDetectionResultSeq

    def __init__(self, *args):
        _ObjectDetectionWrapper.ObjectDetectionResultSeq_swiginit(self, _ObjectDetectionWrapper.new_ObjectDetectionResultSeq(*args))

    def __len__(self):
        return _ObjectDetectionWrapper.ObjectDetectionResultSeq___len__(self)

    def __getitem__(self, i):
        return _ObjectDetectionWrapper.ObjectDetectionResultSeq___getitem__(self, i)

# Register ObjectDetectionResultSeq in _ObjectDetectionWrapper:
_ObjectDetectionWrapper.ObjectDetectionResultSeq_swigregister(ObjectDetectionResultSeq)

class BoundingBox(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _ObjectDetectionWrapper.delete_BoundingBox

    def __init__(self, *args):
        _ObjectDetectionWrapper.BoundingBox_swiginit(self, _ObjectDetectionWrapper.new_BoundingBox(*args))

    def __eq__(self, x):
        return _ObjectDetectionWrapper.BoundingBox___eq__(self, x)

    def __ne__(self, x):
        return _ObjectDetectionWrapper.BoundingBox___ne__(self, x)

    def x(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_x(self, *args)

    def y(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_y(self, *args)

    def width(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_width(self, *args)

    def height(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_height(self, *args)

    def class_name(self, *args):
        return _ObjectDetectionWrapper.BoundingBox_class_name(self, *args)

# Register BoundingBox in _ObjectDetectionWrapper:
_ObjectDetectionWrapper.BoundingBox_swigregister(BoundingBox)

class ObjectDetectionResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _ObjectDetectionWrapper.delete_ObjectDetectionResult

    def __init__(self, *args):
        _ObjectDetectionWrapper.ObjectDetectionResult_swiginit(self, _ObjectDetectionWrapper.new_ObjectDetectionResult(*args))

    def __eq__(self, x):
        return _ObjectDetectionWrapper.ObjectDetectionResult___eq__(self, x)

    def __ne__(self, x):
        return _ObjectDetectionWrapper.ObjectDetectionResult___ne__(self, x)

    def boxes(self, *args):
        return _ObjectDetectionWrapper.ObjectDetectionResult_boxes(self, *args)

# Register ObjectDetectionResult in _ObjectDetectionWrapper:
_ObjectDetectionWrapper.ObjectDetectionResult_swigregister(ObjectDetectionResult)

FASTDDS_GEN_API_VER = _ObjectDetectionWrapper.FASTDDS_GEN_API_VER
class BoundingBoxPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _ObjectDetectionWrapper.BoundingBoxPubSubType_swiginit(self, _ObjectDetectionWrapper.new_BoundingBoxPubSubType())
    __swig_destroy__ = _ObjectDetectionWrapper.delete_BoundingBoxPubSubType

    def serialize(self, data, payload, data_representation):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_compute_key(self, *args)

    def create_data(self):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_create_data(self)

    def delete_data(self, data):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _ObjectDetectionWrapper.BoundingBoxPubSubType_construct_sample(self, memory)

# Register BoundingBoxPubSubType in _ObjectDetectionWrapper:
_ObjectDetectionWrapper.BoundingBoxPubSubType_swigregister(BoundingBoxPubSubType)

class ObjectDetectionResultPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_swiginit(self, _ObjectDetectionWrapper.new_ObjectDetectionResultPubSubType())
    __swig_destroy__ = _ObjectDetectionWrapper.delete_ObjectDetectionResultPubSubType

    def serialize(self, data, payload, data_representation):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_compute_key(self, *args)

    def create_data(self):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_create_data(self)

    def delete_data(self, data):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _ObjectDetectionWrapper.ObjectDetectionResultPubSubType_construct_sample(self, memory)

# Register ObjectDetectionResultPubSubType in _ObjectDetectionWrapper:
_ObjectDetectionWrapper.ObjectDetectionResultPubSubType_swigregister(ObjectDetectionResultPubSubType)



