
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: soafee-practice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ssoonan0770/soafee-practice:flask
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: soafee-practice2
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007 # 외부 접근 가능
  type: NodePort
