apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detector
  namespace: soafee-practice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detector
  template:
    metadata:
      labels:
        app: object-detector
    spec:
      containers:
      - name: object-detector
        image: ssoonan0770/soafee-practice:object_detector
