module LaneDetectionModule
{
    struct LaneLine
    {
        int32 x1;
        int32 y1;
        int32 x2;
        int32 y2;
    };

    struct LaneDetectionResult
    {
        LaneLine left_lane;
        LaneLine right_lane;
    };
};
